# Page Title
page_title: Medication Reminder - Pillify

# App Info
ios_app_id: 1234567890 # Replace with real iOS App ID once published
ios_app_country: us

appstore_link: # Will auto-populate if iOS App ID is correct
playstore_link: # Add Google Play Store link when available
presskit_download_link: https://alicsystems.com/presskit-pillify.zip

app_icon: assets/logo.png
app_name: Medication Reminder - Pillify
app_price: Free with optional subscriptions
app_description: Simple, smart, and reliable medication reminder – never miss a dose again.

enable_smart_app_banner: true

# Information About Yourself
your_name: Alic Systems
your_link: 
your_city: 
email_address: support@alicsystems.com
linkedin_username: 
linkedin_company: 
facebook_username: 
instagram_username: 
twitter_username: 
github_username: 
youtube_username: 
mastodon_link: 

# Feature List
features:
  - title: Smart Medication Management
    description: Easy scheduling for pills, vitamins, and supplements with offline support.
    fontawesome_icon_name: pills


  - title: Simple & User-Friendly
    description: Clean design, quick setup, and flexible scheduling options.
    fontawesome_icon_name: mobile-alt

  - title: Peace of Mind
    description: Track intake history and get reliable reminders every time.
    fontawesome_icon_name: bell

  - title: Perfect for Everyone
    description: Individuals, seniors, caregivers, and families stay on track with ease.
    fontawesome_icon_name: heart



# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black

body_background_color: "#ffffff"
link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

# Jekyll Configuration
sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown
